Anthony-Rondina/UX-Design-Collaboration-Project

- server.js
Updated server with added express.
> Updated server

- server.js
Added Test Comment on line 21 in server.js
> Anthony Test Comment

- server.js
> second test comment added to server.js

- server.js
> create feature branch

- models/User.js
MVP for User Model (will update later tonight after my real job unfortunately...)
> Added MVP for User Model

- controllers/api/userCtrl.js
> Create user controller

- routes/api/users.js
> Created user route

- models/Comment.js
> Added Comments Model

- package.json
- src/pages/App/Homepage/Homepage.js
> homepage file

- models/Art.js
> Added Art Model

- models/Art.js
- models/User.js
> Update user model

- src/components/LoginForm/LoginForm.jsx
> Created LoginForm page. Labels made, input fields made

- routes/api/users.js
Added Show and Delete Routes on Line 15-18
> Updated User Routes to Include Destroy and Show

- controllers/api/artCtrl.js
- controllers/api/userCtrl.js
- routes/api/art.js
Added Art Controller, Art Routes, and Fixed Spelling in User Controller. User Controller fixed line 1 to import User Model with Capital U
> Added Art Controller, Art Routes, and Fixed Spelling in User Controller

- controllers/api/userCtrl.js
Added Lines 67-93 to include Show and Destroy functionality
> Added Destroy and Show Routes to User Controller

- src/components/Logo/Logo.jsx
- src/components/Logo/Logo.module.css
- src/components/SignUpForm/SignUpForm.jsx
- src/components/SignUpForm/SignUpForm.module.css
- src/pages/AuthPage/AuthPage.jsx
- src/pages/AuthPage/AuthPage.module.css
Lots of styling updates made per commits.
> Sign up form

- config/auth.js
- config/checkToken.js
> Created check token file

- config/db.js
> Created database file

- server.js
Updated server file add api user & ensure logged in
> Updated server file

- src/components/ProjectPage/UserProfile.jsx
started basic code for user profile component
> made component

- src/components/LoginForm/LoginForm.jsx
- src/components/SignUpForm/SignUpForm.jsx
- src/components/SignUpForm/SignUpForm.module.css
- src/utilities/send-request.js
- src/utilities/users-api.js
- src/utilities/users-service.js
Added send-request.js, users-api.js and users-service.js
> Add utilities

- src/components/NavHeader/NavHeader.jsx
- src/components/NavHeader/NavHeader.module.css
- src/pages/App/App.css
Added white background to nav bar, added font family to app.css
> updated css

- controllers/api/artCtrl.js
- controllers/api/userCtrl.js
- routes/api/art.js
> API Updates 5-17

- src/components/SignUpForm/SignUpForm.jsx
- src/components/SignUpForm/SignUpForm.module.css
- src/pages/AuthPage/AuthPage.module.css
Password field fixed, Styling to remove the responsiveness within form container fixed.
> Auth page updates

- src/components/ProductPage/UserProfile.js
- src/components/ProductPage/UserProfile.module.css
- src/components/ProductPage/Videos.js
- src/pages/ProductPage/ProductPage.js
- src/pages/ProductPage/ProductPage.module.css
updated userpage and updated product page
> added data to product page

- src/components/SignUpForm/SignUpForm.jsx
- src/components/SignUpForm/SignUpForm.module.css
- src/pages/AuthPage/AuthPage.jsx
- src/pages/AuthPage/AuthPage.module.css
> Sign up updates

- src/components/ArtistCard/ArtistCard.jsx
- src/components/ArtistCard/ArtistCard.module.css
- src/pages/Homepage/Homepage.js
- src/pages/Homepage/Homepage.module.css
images tiled with margin and route to project image added
> css layout updated with Link wrap for image

- src/components/LoginForm/LoginForm.jsx
- src/components/LoginForm/LoginForm.module.css
- src/components/SignUpForm/SignUpForm.module.css
- src/pages/AuthPage/AuthPage.jsx
> Login form updates

- src/components/ProductPage/Comments.js
- src/components/ProductPage/UserProfile.module.css
> added css to comments
